In [1]:
import numpy as np
import pandas as pd

**CREATING A DATAFRAME**

In [4]:
#using dict
data_dict = {                
    'name': ['a','b','c'],
    'age': [18,19,20],
    'city': ['bangalore','tumkur','mangalore'],
    'salary': [70000,100000,50000]
}
df = pd.DataFrame(data_dict)
df

  name  age       city  salary
0    a   18  bangalore   70000
1    b   19     tumkur  100000
2    c   20  mangalore   50000

In [5]:
#using list
data_list= [
    ['a',18,'bangalore',70000],
    ['b',19,'tumkur',100000],
    ['c',20,'mangalore',50000]
]
df2= pd.DataFrame(data_list)
col= ["name","age","city","salary"]
df2= pd.DataFrame(data_list,columns=col)
df2

  name  age       city  salary
0    a   18  bangalore   70000
1    b   19     tumkur  100000
2    c   20  mangalore   50000

**Selection and Indexing of columns**

In [6]:
df2

  name  age       city  salary
0    a   18  bangalore   70000
1    b   19     tumkur  100000
2    c   20  mangalore   50000

In [7]:
df2['name']

0    a
1    b
2    c
Name: name, dtype: object

In [8]:
df2['city']

0    bangalore
1       tumkur
2    mangalore
Name: city, dtype: object

In [9]:
df2[["name","city"]]

  name       city
0    a  bangalore
1    b     tumkur
2    c  mangalore

**Creating a new column**

In [10]:
df2["designation"]= ["student","engineer","doctor"]
df2

  name  age       city  salary designation
0    a   18  bangalore   70000     student
1    b   19     tumkur  100000    engineer
2    c   20  mangalore   50000      doctor

**Removing columns**

In [11]:
df2.drop('designation',axis=1)

  name  age       city  salary
0    a   18  bangalore   70000
1    b   19     tumkur  100000
2    c   20  mangalore   50000

In [12]:
df2

  name  age       city  salary designation
0    a   18  bangalore   70000     student
1    b   19     tumkur  100000    engineer
2    c   20  mangalore   50000      doctor

In [13]:
df2.drop('designation',axis=1,inplace=True)

In [14]:
df2

  name  age       city  salary
0    a   18  bangalore   70000
1    b   19     tumkur  100000
2    c   20  mangalore   50000

In [15]:
df2.drop(["city","salary"],axis=1)

  name  age
0    a   18
1    b   19
2    c   20

In [16]:
df2.drop(0,axis=0)

  name  age       city  salary
1    b   19     tumkur  100000
2    c   20  mangalore   50000

**Selecting rows**

In [17]:
df2

  name  age       city  salary
0    a   18  bangalore   70000
1    b   19     tumkur  100000
2    c   20  mangalore   50000

In [18]:
df2.loc[0]

name              a
age              18
city      bangalore
salary        70000
Name: 0, dtype: object

In [19]:
df2.loc[[0,1]]

  name  age       city  salary
0    a   18  bangalore   70000
1    b   19     tumkur  100000

In [20]:
df2.iloc[0]

name              a
age              18
city      bangalore
salary        70000
Name: 0, dtype: object

**Selecting subsets of rows and columns**

In [21]:
df2.loc[[0,1]][["city","salary"]]

        city  salary
0  bangalore   70000
1     tumkur  100000

In [22]:
df2.loc[[1,2]][["name","age"]]

  name  age
1    b   19
2    c   20

**Conditional selection**

In [23]:
df2

  name  age       city  salary
0    a   18  bangalore   70000
1    b   19     tumkur  100000
2    c   20  mangalore   50000

In [24]:
#selecting whose age is above 19

In [25]:
df2[df2["age"]>19]

  name  age       city  salary
2    c   20  mangalore   50000

In [26]:
#selecting whose salary is above 50000

In [27]:
df2[df2["salary"]>50000]

  name  age       city  salary
0    a   18  bangalore   70000
1    b   19     tumkur  100000

In [28]:
df2[(df2["salary"]>50000) & (df2["city"]=='bangalore')]

  name  age       city  salary
0    a   18  bangalore   70000