In [1]:
import numpy as np
import pandas as pd

**Merging 2 Dataframes**

In [9]:
employee= {
    'employee_id':  [1,2,3,4,5],
    'name': ['sourabha','harshith','priya','preethi','bob'],
    'department': ['CEO','HR','IT','finance','HR']
}
employee=pd.DataFrame(employee)

In [10]:
salaries= {
    'employee_id': [1,2,3,6,7],
    'salary': [110000,100000,50000,60000,40000],
    'bonus':[15000,10000,1000,1200,1300]
}
salary=pd.DataFrame(salaries)

In [11]:
employee

   employee_id      name department
0            1  sourabha        CEO
1            2  harshith         HR
2            3     priya         IT
3            4   preethi    finance
4            5       bob         HR

In [12]:
salary

   employee_id  salary  bonus
0            1  110000  15000
1            2  100000  10000
2            3   50000   1000
3            6   60000   1200
4            7   40000   1300

In [13]:
pd.merge(employee,salary)

   employee_id      name department  salary  bonus
0            1  sourabha        CEO  110000  15000
1            2  harshith         HR  100000  10000
2            3     priya         IT   50000   1000

In [14]:
pd.merge(employee,salary, on='employee_id')

   employee_id      name department  salary  bonus
0            1  sourabha        CEO  110000  15000
1            2  harshith         HR  100000  10000
2            3     priya         IT   50000   1000

In [15]:
pd.merge(employee,salary, on='employee_id',how='inner')

   employee_id      name department  salary  bonus
0            1  sourabha        CEO  110000  15000
1            2  harshith         HR  100000  10000
2            3     priya         IT   50000   1000

In [16]:
pd.merge(employee,salary, on='employee_id',how='outer')

   employee_id      name department    salary    bonus
0            1  sourabha        CEO  110000.0  15000.0
1            2  harshith         HR  100000.0  10000.0
2            3     priya         IT   50000.0   1000.0
3            4   preethi    finance       NaN      NaN
4            5       bob         HR       NaN      NaN
5            6       NaN        NaN   60000.0   1200.0
6            7       NaN        NaN   40000.0   1300.0

In [17]:
pd.merge(employee,salary, on='employee_id',how='left')

   employee_id      name department    salary    bonus
0            1  sourabha        CEO  110000.0  15000.0
1            2  harshith         HR  100000.0  10000.0
2            3     priya         IT   50000.0   1000.0
3            4   preethi    finance       NaN      NaN
4            5       bob         HR       NaN      NaN

In [18]:
pd.merge(employee,salary, on='employee_id',how='right')

   employee_id      name department  salary  bonus
0            1  sourabha        CEO  110000  15000
1            2  harshith         HR  100000  10000
2            3     priya         IT   50000   1000
3            6       NaN        NaN   60000   1200
4            7       NaN        NaN   40000   1300

**Concatination of 2 Dataframes**

In [20]:
df1 = pd.DataFrame({
    'A': ['A0','A1','A2'],
    'B': ['B0','B1','B2'],
    'C': ['C0','C1','C2']
})

In [21]:
df2 = pd.DataFrame({
    'A': ['A3','A4','A5'],
    'B': ['B3','B4','B5'],
    'C': ['C3','C4','C5']
})

In [22]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [23]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [24]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [26]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [27]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [28]:
pd.concat([df1,df2],axis=0)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

**Joining 2 Dataframes**

In [33]:
df1 = pd.DataFrame({
    'name': ['alice','bob','charlie']
}, index=[1,2,3])

In [34]:
df2 = pd.DataFrame({
    'score': [85,90,75]
}, index=[2,3,4])

In [35]:
df1

      name
1    alice
2      bob
3  charlie

In [36]:
df2

   score
2     85
3     90
4     75

In [37]:
df1.join(df2)

      name  score
1    alice    NaN
2      bob   85.0
3  charlie   90.0

In [38]:
df1.join(df2,how='outer')

      name  score
1    alice    NaN
2      bob   85.0
3  charlie   90.0
4      NaN   75.0

In [39]:
df2.join(df1)

   score     name
2     85      bob
3     90  charlie
4     75      NaN